version: '3.8'

services:
  nextcloud:
    image: nextcloud:${VERSION:-latest}
    container_name: nextcloud-${DEPLOYMENT_ID}
    restart: unless-stopped

    environment:
      # Database connection (auto-injected from shared Postgres instance)
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

      # Redis connection (auto-injected from shared Redis instance)
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_HOST_PORT=${REDIS_PORT}

      # NextCloud admin account
      - NEXTCLOUD_ADMIN_USER=${ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}

      # Trusted domains
      - NEXTCLOUD_TRUSTED_DOMAINS=${DOMAIN}

    volumes:
      - nextcloud-data:/var/www/html
      - nextcloud-config:/var/www/html/config

    ports:
      - "${PORT}:80"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/status.php"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  nextcloud-data:
    driver: local
  nextcloud-config:
    driver: local
