// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
// @ts-nocheck
/**
 * Auto-generated TypeScript types from Go models
 * DO NOT EDIT - Run `make types` to regenerate
 */

//////////
// source: application.go

/**
 * Application represents an application that can be deployed
 */
export interface Application {
  id: string;
  name: string;
  slug: string;
  category: string;
  description: string;
  icon_url?: string;
  docker_image: string;
  required_ram: number /* int64 */; // bytes
  required_storage: number /* int64 */; // bytes
  config_template: string;
  setup_steps?: string;
  created_at: string;
  updated_at: string;
}

//////////
// source: deployment.go

/**
 * DeploymentStatus represents the status of a deployment
 */
export type DeploymentStatus = string;
export const DeploymentStatusValidating: DeploymentStatus = "validating";
export const DeploymentStatusPreparing: DeploymentStatus = "preparing";
export const DeploymentStatusDeploying: DeploymentStatus = "deploying";
export const DeploymentStatusConfiguring: DeploymentStatus = "configuring";
export const DeploymentStatusHealthCheck: DeploymentStatus = "health_check";
export const DeploymentStatusRunning: DeploymentStatus = "running";
export const DeploymentStatusStopped: DeploymentStatus = "stopped";
export const DeploymentStatusFailed: DeploymentStatus = "failed";
export const DeploymentStatusRollingBack: DeploymentStatus = "rolling_back";
export const DeploymentStatusRolledBack: DeploymentStatus = "rolled_back";
/**
 * Deployment represents a deployed application on a device
 */
export interface Deployment {
  id: string;
  recipe_slug: string;
  recipe_name: string;
  application_id: string;
  application?: Application;
  device_id: string;
  device?: Device;
  status: DeploymentStatus;
  config?: string;
  domain?: string;
  internal_port: number /* int */;
  external_port?: number /* int */;
  container_id?: string;
  compose_project?: string;
  generated_compose?: string; // For debugging/transparency
  deployment_logs?: string; // Logs from deployment process
  ssh_commands?: string; // For debugging
  rollback_log?: string; // For debugging
  error_details?: string;
  deployed_at?: string;
  created_at: string;
  updated_at: string;
}

//////////
// source: device.go

/**
 * DeviceType represents the type of device
 */
export type DeviceType = string;
export const DeviceTypeRouter: DeviceType = "router";
export const DeviceTypeServer: DeviceType = "server";
export const DeviceTypeNAS: DeviceType = "nas";
export const DeviceTypeSwitch: DeviceType = "switch";
/**
 * DeviceStatus represents the current status of a device
 */
export type DeviceStatus = string;
export const DeviceStatusOnline: DeviceStatus = "online";
export const DeviceStatusOffline: DeviceStatus = "offline";
export const DeviceStatusError: DeviceStatus = "error";
export const DeviceStatusUnknown: DeviceStatus = "unknown";
/**
 * Device represents a managed device (server, router, NAS, etc.)
 */
export interface Device {
  id: string;
  name: string;
  type: DeviceType;
  ip_address: string;
  mac_address?: string;
  status: DeviceStatus;
  metadata?: string;
  last_seen?: string;
  created_at: string;
  updated_at: string;
}
