// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
// @ts-nocheck
/**
 * Auto-generated TypeScript types from Go models
 * DO NOT EDIT - Run `make types` to regenerate
 */

//////////
// source: apierror.go

/**
 * Error codes for structured error handling
 */
export const ErrCodeSudoNotConfigured = "SUDO_NOT_CONFIGURED";
/**
 * Error codes for structured error handling
 */
export const ErrCodeSSHConnectionFailed = "SSH_CONNECTION_FAILED";
/**
 * Error codes for structured error handling
 */
export const ErrCodeAuthFailed = "AUTH_FAILED";
/**
 * Error codes for structured error handling
 */
export const ErrCodeNotFound = "NOT_FOUND";
/**
 * Error codes for structured error handling
 */
export const ErrCodeAlreadyExists = "ALREADY_EXISTS";
/**
 * Error codes for structured error handling
 */
export const ErrCodeValidationFailed = "VALIDATION_FAILED";
/**
 * Error codes for structured error handling
 */
export const ErrCodeInternalError = "INTERNAL_ERROR";
/**
 * APIError represents a structured error with code and optional details
 */
export interface APIError {
  code: string;
  message: string;
  details?: { [key: string]: any};
}

//////////
// source: application.go

/**
 * Application represents an application that can be deployed
 */
export interface Application {
  id: string;
  name: string;
  slug: string;
  category: string;
  description: string;
  icon_url?: string;
  docker_image: string;
  required_ram: number /* int64 */; // bytes
  required_storage: number /* int64 */; // bytes
  config_template: string;
  setup_steps?: string;
  created_at: string;
  updated_at: string;
}

//////////
// source: credential.go

/**
 * CredentialType represents the type of authentication
 */
export type CredentialType = string;
export const CredentialTypePassword: CredentialType = "password";
export const CredentialTypeSSHKey: CredentialType = "ssh_key";
/**
 * Credential represents stored authentication credentials for devices
 * tygo:emit
 */
export interface Credential {
  id: string;
  name: string; // User-friendly name like "Home Network Default"
  type: CredentialType;
  username: string;
  password?: string; // Encrypted
  ssh_key?: string; // Encrypted private key
  /**
   * Matching criteria - used to auto-apply credentials
   */
  network_cidr?: string; // e.g., "192.168.1.0/24"
  device_type?: string; // e.g., "server", "nas"
  host_pattern?: string; // e.g., "*synology*", "*nas*"
  /**
   * Usage tracking
   */
  last_used?: string;
  use_count: number /* int */;
  created_at: string;
  updated_at: string;
}

//////////
// source: deployment.go

/**
 * DeploymentStatus represents the status of a deployment
 */
export type DeploymentStatus = string;
export const DeploymentStatusValidating: DeploymentStatus = "validating";
export const DeploymentStatusPreparing: DeploymentStatus = "preparing";
export const DeploymentStatusDeploying: DeploymentStatus = "deploying";
export const DeploymentStatusConfiguring: DeploymentStatus = "configuring";
export const DeploymentStatusHealthCheck: DeploymentStatus = "health_check";
export const DeploymentStatusRunning: DeploymentStatus = "running";
export const DeploymentStatusStopped: DeploymentStatus = "stopped";
export const DeploymentStatusFailed: DeploymentStatus = "failed";
export const DeploymentStatusRollingBack: DeploymentStatus = "rolling_back";
export const DeploymentStatusRolledBack: DeploymentStatus = "rolled_back";
/**
 * Deployment represents a deployed application on a device
 */
export interface Deployment {
  id: string;
  recipe_slug: string; // Marketplace recipe identifier
  recipe_name: string; // Cached for display
  application_id?: string; // Legacy - made nullable
  application?: Application;
  device_id: string;
  device?: Device;
  status: DeploymentStatus;
  config?: string;
  domain?: string;
  internal_port: number /* int */;
  external_port?: number /* int */;
  container_id?: string;
  /**
   * DNS-friendly access configuration
   */
  hostname?: string; // DNS hostname (e.g., "vaultwarden.server1.home.arpa")
  url?: string; // Full access URL (e.g., "https://vaultwarden.server1.home.arpa")
  use_traefik: boolean; // Whether to use Traefik for routing
  orchestrator_mode: string; // "compose" or "swarm"
  compose_project?: string; // Docker Compose project name
  generated_compose?: string; // For debugging/transparency
  deployment_logs?: string; // Logs from deployment process
  ssh_commands?: string; // For debugging
  rollback_log?: string; // For debugging
  error_details?: string;
  deployed_at?: string;
  created_at: string;
  updated_at: string;
}

//////////
// source: device.go

/**
 * DeviceType represents the type of device
 */
export type DeviceType = string;
export const DeviceTypeRouter: DeviceType = "router";
export const DeviceTypeServer: DeviceType = "server";
export const DeviceTypeNAS: DeviceType = "nas";
export const DeviceTypeSwitch: DeviceType = "switch";
/**
 * DeviceStatus represents the current status of a device
 */
export type DeviceStatus = string;
export const DeviceStatusOnline: DeviceStatus = "online";
export const DeviceStatusOffline: DeviceStatus = "offline";
export const DeviceStatusError: DeviceStatus = "error";
export const DeviceStatusUnknown: DeviceStatus = "unknown";
/**
 * AuthType represents the authentication method for SSH
 */
export type AuthType = string;
export const AuthTypeAuto: AuthType = "auto"; // SSH agent or default keys
export const AuthTypePassword: AuthType = "password"; // Password authentication
export const AuthTypeSSHKey: AuthType = "ssh_key"; // SSH key authentication
export const AuthTypeTailscale: AuthType = "tailscale"; // Tailscale SSH (uses Tailscale's built-in SSH)
/**
 * PrimaryConnection represents which connection type to use first
 */
export type PrimaryConnection = string;
export const PrimaryConnectionLocal: PrimaryConnection = "local"; // Use local IP address first
export const PrimaryConnectionTailscale: PrimaryConnection = "tailscale"; // Use Tailscale address first
/**
 * Device represents a managed device (server, router, NAS, etc.)
 */
export interface Device {
  id: string;
  name: string;
  type: DeviceType;
  local_ip_address: string;
  tailscale_address?: string; // Tailscale IP or hostname (optional)
  primary_connection: PrimaryConnection; // Which connection to try first
  mac_address?: string;
  domain_suffix?: string; // Domain suffix for apps (e.g., "server1.home.arpa")
  status: DeviceStatus;
  username: string; // SSH username (not sensitive)
  auth_type: AuthType; // Authentication method
  metadata?: string;
  /**
   * Current resource metrics (updated by ResourceMonitoringService)
   */
  cpu_usage_percent?: number /* float64 */;
  cpu_cores?: number /* int */;
  total_ram_mb?: number /* int */;
  used_ram_mb?: number /* int */;
  available_ram_mb?: number /* int */;
  total_storage_gb?: number /* int */;
  used_storage_gb?: number /* int */;
  available_storage_gb?: number /* int */;
  resources_updated_at?: string;
  last_seen?: string;
  created_at: string;
  updated_at: string;
}

//////////
// source: device_metrics.go

/**
 * DeviceMetrics represents resource usage metrics for a device at a point in time
 */
export interface DeviceMetrics {
  id: string;
  device_id: string;
  device?: Device;
  cpu_usage_percent: number /* float64 */;
  cpu_cores: number /* int */;
  total_ram_mb: number /* int */;
  used_ram_mb: number /* int */;
  available_ram_mb: number /* int */;
  total_storage_gb: number /* int */;
  used_storage_gb: number /* int */;
  available_storage_gb: number /* int */;
  recorded_at: string;
  created_at: string;
}

//////////
// source: nfs.go

/**
 * NFSExport represents an NFS export configured on a server device
 */
export interface NFSExport {
  id: string;
  device_id: string; // The NFS server
  path: string; // e.g., "/srv/nfs/shared"
  client_cidr: string; // e.g., "*", "192.168.1.0/24"
  options: string;
  active: boolean;
  created_at: string;
  updated_at: string;
}
/**
 * NFSMount represents an NFS mount on a client device
 */
export interface NFSMount {
  id: string;
  device_id: string; // The NFS client
  server_ip: string; // NFS server IP
  remote_path: string; // e.g., "/srv/nfs/shared"
  local_path: string; // e.g., "/mnt/nfs/shared"
  options: string;
  permanent: boolean; // Add to /etc/fstab
  active: boolean;
  created_at: string;
  updated_at: string;
}

//////////
// source: recipe.go

/**
 * Recipe represents a marketplace application recipe loaded from YAML
 */
export interface Recipe {
  /**
   * Basic Information
   */
  id: string;
  name: string;
  slug: string;
  category: string;
  tagline: string;
  description: string;
  /**
   * Branding
   */
  icon_url: string;
  author: string;
  website: string;
  source_code: string;
  /**
   * Resource Requirements (for intelligent scheduler)
   */
  requirements: RecipeRequirements;
  /**
   * User Configuration
   */
  config_options: RecipeConfigOption[];
  /**
   * Database Provisioning (intelligent database pooling)
   */
  database: RecipeDatabaseConfig;
  /**
   * Cache Provisioning
   */
  cache: RecipeCacheConfig;
  /**
   * Volume Configuration
   */
  volumes: { [key: string]: RecipeVolumeConfig};
  /**
   * Post-deployment automation
   */
  post_install: RecipePostInstallStep[];
  /**
   * Health monitoring
   */
  health: RecipeHealthConfig;
  /**
   * Update configuration
   */
  updates: RecipeUpdateConfig;
  /**
   * Curated Marketplace Features (NEW)
   */
  saas_replacements?: SaaSReplacement[];
  difficulty_level?: string; // "beginner", "intermediate", "advanced"
  setup_time_minutes?: number /* int */; // Estimated setup time
  feature_highlights?: string[]; // Key features for comparison tables
  is_infrastructure?: boolean; // Infrastructure template (e.g., laravel-app-server)
  server_type?: string; // "app_server", "web_server", "database_server", "worker_server", "cache_server"
  /**
   * Dependency Auto-Provisioning (NEW)
   */
  dependencies?: RecipeDependencies;
  /**
   * Legacy field
   */
  post_deploy_instructions?: string;
  /**
   * Legacy Resources field for backward compatibility
   */
  resources?: RecipeResources;
  /**
   * Legacy HealthCheck field
   */
  health_check?: RecipeHealthCheck;
}
/**
 * RecipeMetadata contains metadata about the recipe source and versioning
 */
export interface RecipeMetadata {
  source: string; // Recipe source (currently only "local")
  version: string; // Recipe version
  last_updated: string; // When recipe was last updated
  updated_at: string; // When we last fetched it
  source_url: string; // URL to source repository
  image_version: string; // Latest Docker image version
  quality_score: number /* int */; // 0-100 quality score
  verified: boolean; // Is this a verified/official recipe
  deploy_count: number /* int */; // How many times deployed (local tracking)
  success_rate: number /* float64 */; // Deployment success rate (0-1)
}
/**
 * RecipeResources defines the resource requirements for a recipe
 */
export interface RecipeResources {
  min_ram_mb: number /* int */;
  min_storage_gb: number /* int */;
  recommended_ram_mb: number /* int */;
  recommended_storage_gb: number /* int */;
  cpu_cores: number /* int */;
}
/**
 * RecipeConfigOption defines a user-configurable option
 */
export interface RecipeConfigOption {
  name: string;
  label: string;
  type: string; // string, number, boolean
  default: any;
  required: boolean;
  description: string;
}
/**
 * RecipeHealthCheck defines health check parameters (legacy)
 */
export interface RecipeHealthCheck {
  path: string;
  port: number /* int */; // Port to check (defaults to 80 if not specified)
  expected_status: number /* int */;
  timeout_seconds: number /* int */;
}
/**
 * RecipeRequirements defines resource requirements for intelligent scheduling
 */
export interface RecipeRequirements {
  memory: {
    minimum: string; // e.g., "512MB"
    recommended: string; // e.g., "1GB"
  };
  storage: {
    minimum: string; // e.g., "1GB"
    recommended: string; // e.g., "5GB"
    type: string; // "ssd", "hdd", "any"
  };
  cpu: {
    minimum_cores: number /* int */;
    recommended_cores: number /* int */;
  };
  reliability: string; // "high", "medium", "low"
  always_on: boolean;
}
/**
 * RecipeDatabaseConfig defines database provisioning configuration
 */
export interface RecipeDatabaseConfig {
  engine: string; // "postgres", "mysql", "mariadb", "sqlite", "none"
  auto_provision: boolean; // Enable automatic database provisioning
  version?: string; // Database version (e.g., "15" for postgres)
  env_prefix?: string; // Prefix for env vars (default: "DB_")
}
/**
 * RecipeCacheConfig defines cache provisioning configuration
 */
export interface RecipeCacheConfig {
  engine: string; // "redis", "memcached", "none"
  auto_provision: boolean; // Enable automatic cache provisioning
  version?: string; // Cache version
  env_prefix?: string; // Prefix for env vars (default: "REDIS_" or "MEMCACHED_")
}
/**
 * RecipeVolumeConfig defines volume configuration
 */
export interface RecipeVolumeConfig {
  description: string;
  size_estimate: string; // e.g., "5GB"
  backup_priority: string; // "high", "medium", "low"
  backup_frequency: string; // "daily", "weekly", "monthly"
}
/**
 * RecipePostInstallStep defines a post-installation action
 */
export interface RecipePostInstallStep {
  type: string; // "message", "command", "webhook"
  title?: string;
  message?: string;
  command?: string;
  url?: string;
}
/**
 * RecipeHealthConfig defines health monitoring configuration
 */
export interface RecipeHealthConfig {
  endpoint: string; // Health check HTTP path
  interval: string; // e.g., "30s"
  timeout: string; // e.g., "10s"
  unhealthy_threshold: number /* int */; // Failures before marking unhealthy
}
/**
 * RecipeUpdateConfig defines update behavior
 */
export interface RecipeUpdateConfig {
  strategy: string; // "automatic", "manual", "notify"
  backup_before_update: boolean; // Create backup before updating
  rollback_on_failure: boolean; // Auto-rollback if update fails
}
/**
 * SaaSReplacement defines which SaaS service this recipe replaces
 */
export interface SaaSReplacement {
  name: string; // e.g., "Google Photos"
  comparison_url?: string; // URL to comparison guide
}
/**
 * RecipeDependencies defines required and recommended dependencies
 */
export interface RecipeDependencies {
  required?: RecipeDependency[];
  recommended?: RecipeDependency[];
}
/**
 * RecipeDependency represents a single dependency
 */
export interface RecipeDependency {
  type: string; // "reverse_proxy", "database", "cache", "application", "infrastructure"
  name?: string; // Specific app name (for application dependencies)
  engine?: string; // Database/cache engine (for database/cache dependencies)
  min_version?: string; // Minimum version required
  prefer?: string; // Preferred option (e.g., "traefik")
  alternatives?: string[]; // Alternative options
  shared?: boolean; // Use shared instance (default true for DB/cache)
  auto_provision?: boolean; // Auto-provision if missing (default true)
  auto_configure?: boolean; // Auto-configure connection
  purpose?: string; // Human-readable purpose
  message?: string; // Custom message to show user
  for_volumes?: string[]; // Volumes to backup (for backup dependencies)
}

//////////
// source: shared_cache.go

/**
 * SharedCacheInstance represents a shared cache server (Redis/Memcached)
 * Used by CachePoolManager for resource-efficient cache provisioning
 */
export interface SharedCacheInstance {
  id: string;
  device_id: string;
  engine: string; // redis, memcached
  version: string;
  name: string; // e.g., "shared-redis"
  port: number /* int */; // Composite index with DeviceID for efficient port lookups
  container_name: string;
  max_memory_mb: number /* int */;
  status: string; // provisioning, running, stopped, error (indexed for efficient status queries)
  created_at: string;
  updated_at: string;
}
/**
 * ProvisionedCacheConfig represents per-application cache configuration within a shared instance
 */
export interface ProvisionedCacheConfig {
  id: string;
  cache_instance_id: string;
  app_slug: string;
  device_id: string;
  database_number: number /* int */; // Redis database number (0-15), set to 0 for Memcached (unused)
  key_prefix: string; // Optional key prefix for isolation
  max_memory_mb: number /* int */; // Memory limit for this app
  created_at: string;
  updated_at: string;
  /**
   * Foreign key
   */
  cache_instance?: SharedCacheInstance;
}

//////////
// source: shared_database.go

/**
 * SharedDatabaseInstance represents a shared database container running on a device
 * Multiple applications can have isolated databases within a single shared instance
 */
export interface SharedDatabaseInstance {
  id: string;
  device_id: string;
  device?: Device;
  engine: string; // "postgres", "mysql", "mariadb"
  version: string; // e.g., "15", "8.0"
  status: string; // "provisioning", "running", "failed", "stopped"
  /**
   * Container information
   */
  container_id?: string;
  container_name: string; // e.g., "homelab-postgres-shared"
  compose_project: string; // Docker Compose project name
  /**
   * Connection details
   */
  port: number /* int */; // Exposed port on device
  internal_port: number /* int */; // Container internal port (5432 for postgres, 3306 for mysql)
  /**
   * Master credentials (encrypted in credential store)
   */
  master_username: string; // Usually "postgres" or "root"
  /**
   * Resource tracking
   */
  estimated_ram_mb: number /* int */; // Estimated RAM usage
  database_count: number /* int */; // Number of databases in this instance
  /**
   * Metadata
   */
  deployed_at?: string;
  last_health_check?: string;
  error_details?: string;
  created_at: string;
  updated_at: string;
}
/**
 * ProvisionedDatabase represents an isolated database within a shared database instance
 */
export interface ProvisionedDatabase {
  id: string;
  shared_database_instance_id: string;
  shared_instance?: SharedDatabaseInstance;
  deployment_id: string; // One database per deployment
  deployment?: Deployment;
  /**
   * Database details
   */
  database_name: string; // e.g., "nextcloud_abc123"
  username: string; // e.g., "nextcloud_user"
  /**
   * Connection string components (injected as env vars into application)
   */
  host: string; // Device IP or hostname
  port: number /* int */; // Shared instance port
  /**
   * Status
   */
  status: string; // "provisioning", "ready", "failed"
  error_details?: string;
  /**
   * Metadata
   */
  provisioned_at?: string;
  created_at: string;
  updated_at: string;
}

//////////
// source: software.go

/**
 * SoftwareType represents the type of software
 */
export type SoftwareType = string;
export const SoftwareDocker: SoftwareType = "docker";
export const SoftwareDockerCompose: SoftwareType = "docker-compose";
export const SoftwareNFSServer: SoftwareType = "nfs-server";
export const SoftwareNFSClient: SoftwareType = "nfs-client";
/**
 * InstalledSoftware tracks software installed on devices
 */
export interface InstalledSoftware {
  id: string;
  device_id: string;
  name: SoftwareType;
  version: string;
  installed_at: string;
  installed_by: string; // username or "system"
  created_at: string;
  updated_at: string;
}

//////////
// source: software_definition.go

/**
 * SoftwareDefinition defines how to manage a specific piece of software
 */
export interface SoftwareDefinition {
  id: string; // Unique identifier (e.g., "docker")
  name: string; // Display name (e.g., "Docker Engine")
  description: string; // Short description
  category: string; // Category (e.g., "container", "storage", "database")
  icon: string; // Icon name or URL
  commands: SoftwareCommands; // Commands for managing the software
  options: { [key: string]: string}; // Additional options/metadata
}
/**
 * SoftwareCommands defines the shell commands for managing software
 */
export interface SoftwareCommands {
  /**
   * CheckInstalled returns exit code 0 if installed, non-zero otherwise
   * Should output version info to stdout
   */
  check_installed: string;
  /**
   * CheckVersion returns the currently installed version
   */
  check_version: string;
  /**
   * CheckUpdates checks if updates are available
   * Should output "updates available" or similar to stdout if updates exist
   */
  check_updates: string;
  /**
   * Install installs the software
   */
  install: string;
  /**
   * Update updates the software to the latest version
   */
  update: string;
  /**
   * Uninstall removes the software (optional, can be empty)
   */
  uninstall: string;
  /**
   * PostInstall runs after successful installation (optional)
   */
  post_install: string;
  /**
   * PreUninstall runs before uninstallation (optional)
   */
  pre_uninstall: string;
}
/**
 * SoftwareUpdateInfo represents update availability information
 */
export interface SoftwareUpdateInfo {
  software_id: string;
  current_version: string;
  available_version?: string;
  update_available: boolean;
  message?: string;
}

//////////
// source: software_installation.go

/**
 * SoftwareInstallationStatus represents the status of a software installation
 */
export type SoftwareInstallationStatus = string;
export const InstallationStatusPending: SoftwareInstallationStatus = "pending";
export const InstallationStatusInstalling: SoftwareInstallationStatus = "installing";
export const InstallationStatusSuccess: SoftwareInstallationStatus = "success";
export const InstallationStatusFailed: SoftwareInstallationStatus = "failed";
/**
 * SoftwareInstallation represents a software installation job
 */
export interface SoftwareInstallation {
  id: string;
  device_id: string;
  software_name: SoftwareType;
  status: SoftwareInstallationStatus;
  install_logs?: string;
  error_details?: string;
  created_at: string;
  completed_at?: string;
  /**
   * Relationships
   */
  device?: Device;
}

//////////
// source: user.go

/**
 * User represents a user account in the system
 */
export interface User {
  id: string;
  username: string;
  email: string; // Optional
  is_admin: boolean;
  created_at: string;
  updated_at: string;
}

//////////
// source: volume.go

/**
 * VolumeType represents the type of Docker volume
 */
export type VolumeType = string;
export const VolumeTypeLocal: VolumeType = "local";
export const VolumeTypeNFS: VolumeType = "nfs";
/**
 * Volume represents a Docker volume
 */
export interface Volume {
  id: string;
  device_id: string;
  name: string;
  type: VolumeType;
  driver: string;
  driver_opts?: string; // JSON map of driver options
  nfs_server_ip?: string;
  nfs_path?: string;
  size: number /* int64 */; // bytes, if known
  in_use: boolean;
  created_at: string;
  updated_at: string;
}
