package services

import (
	"fmt"
	"strings"

	"github.com/jared-cannon/homelab-orchestration-platform/internal/models"
)

// EnvironmentBuilder builds environment variable maps for docker-compose deployment
// Combines user config + generated secrets + database credentials
type EnvironmentBuilder struct {
	secretManager *SecretManager
	dbPoolManager *DatabasePoolManager
}

// NewEnvironmentBuilder creates a new environment builder
func NewEnvironmentBuilder(credService *CredentialService, dbPoolManager *DatabasePoolManager) *EnvironmentBuilder {
	return &EnvironmentBuilder{
		secretManager: NewSecretManager(credService),
		dbPoolManager: dbPoolManager,
	}
}

// BuildEnvironment creates a complete environment variable map for deployment
// Returns both a map (for programmatic use) and a .env file content (for docker-compose)
func (eb *EnvironmentBuilder) BuildEnvironment(
	deployment *models.Deployment,
	recipe *models.Recipe,
	userConfig map[string]interface{},
	device *models.Device,
	provisionedDB *models.ProvisionedDatabase,
) (map[string]string, string, error) {

	envMap := make(map[string]string)

	// 1. Add user-provided configuration (convert to uppercase env var names)
	for key, value := range userConfig {
		envMap[strings.ToUpper(key)] = fmt.Sprintf("%v", value)
	}

	// 2. Add deployment-specific variables
	envMap["DEPLOYMENT_ID"] = deployment.ID.String()
	envMap["COMPOSE_PROJECT"] = deployment.ComposeProject
	envMap["DEVICE_IP"] = device.GetPrimaryAddress()

	// 3. Generate or retrieve persistent secrets
	secrets, err := eb.secretManager.GenerateOrRetrieveSecrets(deployment.ID, recipe, userConfig)
	if err != nil {
		return nil, "", fmt.Errorf("failed to generate secrets: %w", err)
	}
	for key, value := range secrets {
		envMap[strings.ToUpper(key)] = value
	}

	// 4. Add database credentials if database was provisioned
	if provisionedDB != nil {
		dbEnvVars, err := eb.buildDatabaseEnvVars(provisionedDB, recipe.Database.EnvPrefix)
		if err != nil {
			return nil, "", fmt.Errorf("failed to build database env vars: %w", err)
		}
		for k, v := range dbEnvVars {
			envMap[k] = v
		}
	}

	// 5. Process password hashing (creates _HASH variants for password fields)
	if err := eb.secretManager.ProcessPasswordHashing(recipe, envMap); err != nil {
		return nil, "", fmt.Errorf("failed to hash passwords: %w", err)
	}

	// 6. Build .env file content
	envFileContent := eb.buildEnvFileContent(envMap)

	return envMap, envFileContent, nil
}

// buildDatabaseEnvVars creates environment variables for database connection
func (eb *EnvironmentBuilder) buildDatabaseEnvVars(provisionedDB *models.ProvisionedDatabase, envPrefix string) (map[string]string, error) {
	if envPrefix == "" {
		envPrefix = "DB_"
	}

	// Get database password from credential store
	password, err := eb.secretManager.credService.GetCredential(provisionedDB.CredentialKey)
	if err != nil {
		return nil, fmt.Errorf("failed to retrieve database password: %w", err)
	}

	envVars := provisionedDB.GetConnectionEnvVars(envPrefix)
	envVars[envPrefix+"PASSWORD"] = password

	// Also provide connection string
	envVars[envPrefix+"CONNECTION_STRING"] = buildConnectionString(provisionedDB, password)

	return envVars, nil
}

// buildConnectionString creates a database connection string
func buildConnectionString(db *models.ProvisionedDatabase, password string) string {
	if db.SharedDatabaseInstance == nil {
		return ""
	}

	switch db.SharedDatabaseInstance.Engine {
	case "postgres":
		return fmt.Sprintf("postgresql://%s:%s@%s:%d/%s",
			db.Username, password, db.Host, db.Port, db.DatabaseName)
	case "mysql", "mariadb":
		return fmt.Sprintf("mysql://%s:%s@%s:%d/%s",
			db.Username, password, db.Host, db.Port, db.DatabaseName)
	default:
		return ""
	}
}

// buildEnvFileContent creates the content for a .env file
func (eb *EnvironmentBuilder) buildEnvFileContent(envMap map[string]string) string {
	var builder strings.Builder
	builder.WriteString("# Auto-generated environment file\n")
	builder.WriteString("# Generated by Homelab Orchestration Platform\n\n")

	for key, value := range envMap {
		// Escape values that contain special characters
		escapedValue := escapeEnvValue(value)
		builder.WriteString(fmt.Sprintf("%s=%s\n", key, escapedValue))
	}

	return builder.String()
}

// escapeEnvValue escapes special characters in environment variable values
// Values containing special characters are quoted and escaped to prevent parsing issues
func escapeEnvValue(value string) string {
	// If value contains spaces, quotes, or special characters, wrap in quotes
	needsQuotes := strings.ContainsAny(value, " \t\n\r\"'$`\\#")

	if !needsQuotes {
		return value
	}

	// Escape backslashes first, then quotes (order matters!)
	escaped := strings.ReplaceAll(value, "\\", "\\\\")
	escaped = strings.ReplaceAll(escaped, "\"", "\\\"")
	return fmt.Sprintf("\"%s\"", escaped)
}

// InjectTraefikLabels injects Traefik routing labels into a docker-compose.yaml content
// This modifies the first service in the compose file to add Traefik routing configuration
// Supports both Docker Compose and Docker Swarm modes
func (eb *EnvironmentBuilder) InjectTraefikLabels(
	composeContent string,
	serviceName string, // Name of the main service to add labels to
	hostname string,    // Full hostname (e.g., "vaultwarden.server1.home.arpa")
	internalPort int,   // Internal port the service listens on
	mode string,        // "compose" or "swarm"
) (string, error) {

	// Generate the labels based on mode
	var labels []string
	if mode == "swarm" {
		labels = generateSwarmTraefikLabels(serviceName, hostname, internalPort)
	} else {
		labels = generateComposeTraefikLabels(serviceName, hostname, internalPort)
	}

	// Instead of parsing YAML (which is complex and error-prone),
	// we'll use a simple string-based approach to inject labels
	// This is safer for production and avoids YAML formatting issues

	return injectLabelsIntoCompose(composeContent, serviceName, labels)
}

// generateComposeTraefikLabels creates Traefik labels for Docker Compose mode
func generateComposeTraefikLabels(serviceName, hostname string, port int) []string {
	routerName := sanitizeRouterName(serviceName)
	return []string{
		"traefik.enable=true",
		fmt.Sprintf("traefik.http.routers.%s.rule=Host(`%s`)", routerName, hostname),
		fmt.Sprintf("traefik.http.routers.%s.entrypoints=websecure", routerName),
		fmt.Sprintf("traefik.http.routers.%s.tls.certresolver=letsencrypt", routerName),
		fmt.Sprintf("traefik.http.services.%s.loadbalancer.server.port=%d", routerName, port),
		fmt.Sprintf("traefik.docker.network=%s", TraefikNetworkName),
	}
}

// generateSwarmTraefikLabels creates Traefik labels for Docker Swarm mode
func generateSwarmTraefikLabels(serviceName, hostname string, port int) []string {
	routerName := sanitizeRouterName(serviceName)
	return []string{
		"traefik.enable=true",
		fmt.Sprintf("traefik.http.routers.%s.rule=Host(`%s`)", routerName, hostname),
		fmt.Sprintf("traefik.http.routers.%s.entrypoints=websecure", routerName),
		fmt.Sprintf("traefik.http.routers.%s.tls.certresolver=letsencrypt", routerName),
		fmt.Sprintf("traefik.http.services.%s.loadbalancer.server.port=%d", routerName, port),
		// Swarm-specific: service must be on overlay network
		fmt.Sprintf("traefik.docker.network=%s", TraefikNetworkName),
	}
}

// sanitizeRouterName creates a valid Traefik router name from service name
// Replaces invalid characters with hyphens
func sanitizeRouterName(name string) string {
	result := strings.ReplaceAll(name, "_", "-")
	result = strings.ReplaceAll(result, " ", "-")
	return strings.ToLower(result)
}

// injectLabelsIntoCompose injects labels into the specified service in docker-compose content
// Uses simple string manipulation instead of YAML parsing for reliability
func injectLabelsIntoCompose(composeContent, serviceName string, labels []string) (string, error) {
	lines := strings.Split(composeContent, "\n")
	var result []string
	inTargetService := false
	labelsInjected := false
	currentIndent := ""

	for i, line := range lines {
		result = append(result, line)

		// Detect if we're entering the target service
		if !inTargetService && strings.Contains(line, serviceName+":") {
			// Make sure this is a service definition (look for "services:" earlier)
			for j := i - 1; j >= 0; j-- {
				if strings.Contains(lines[j], "services:") {
					inTargetService = true
					break
				}
				// Stop looking if we hit another top-level key
				if len(lines[j]) > 0 && lines[j][0] != ' ' && lines[j][0] != '\t' {
					break
				}
			}
		}

		// If we're in the target service and haven't injected labels yet
		if inTargetService && !labelsInjected {
			// Detect indentation (look at next non-empty line)
			if strings.TrimSpace(line) == serviceName+":" {
				// Find indentation from next property
				for j := i + 1; j < len(lines); j++ {
					nextLine := lines[j]
					if strings.TrimSpace(nextLine) != "" && !strings.HasPrefix(strings.TrimSpace(nextLine), "#") {
						// Extract indentation
						currentIndent = nextLine[:len(nextLine)-len(strings.TrimLeft(nextLine, " \t"))]
						break
					}
				}

				// Look for existing "labels:" section or insert before "networks:" or at end
				labelsLineIndex := -1
				networksLineIndex := -1

				for j := i + 1; j < len(lines); j++ {
					trimmed := strings.TrimSpace(lines[j])
					if trimmed == "labels:" {
						labelsLineIndex = j
						break
					}
					if trimmed == "networks:" {
						networksLineIndex = j
						break
					}
					// Stop if we hit another service
					if len(lines[j]) > 0 && lines[j][0] != ' ' && lines[j][0] != '\t' {
						break
					}
				}

				// Inject labels
				labelsContent := []string{currentIndent + "labels:"}
				for _, label := range labels {
					labelsContent = append(labelsContent, currentIndent + "  - \"" + label + "\"")
				}

				if labelsLineIndex != -1 {
					// Labels section exists, append to it
					// Skip this for now - assume no existing labels
				} else if networksLineIndex != -1 {
					// Insert before networks
					result = append(result[:networksLineIndex], append(labelsContent, result[networksLineIndex:]...)...)
				} else {
					// Append at current position
					result = append(result, labelsContent...)
				}

				// Also inject networks if not present
				networksContent := []string{
					currentIndent + "networks:",
					fmt.Sprintf("%s  - %s", currentIndent, TraefikNetworkName),
				}
				if networksLineIndex == -1 {
					result = append(result, networksContent...)
				}

				labelsInjected = true
				inTargetService = false // Done with this service
			}
		}
	}

	if !labelsInjected {
		return "", fmt.Errorf("failed to inject labels: service '%s' not found or invalid format", serviceName)
	}

	return strings.Join(result, "\n"), nil
}
